my_lab/my_lab/apps/movie/urls.py
from django.urls import path
from my_lab import settings
from . import views

urlpatterns = [
    path("", views.RentView.as_view(), name="home"),
    path("movies/", views.MoviesView.as_view(), name="movie_views"),
    path("movies/details/<int:id>/", views.MovieDetailView.as_view()),
    path("members/", views.MembersView.as_view(), name="member_views"),
    path("rent/", views.MovieRentalView.as_view()),
    path("rent/success", views.MoveRentalSuccessView.as_view()),
    path("member/rental", views.MemberRentalInfoView.as_view()),
    path("movie/create/", views.MovieCreateView.as_view()),
    path("movie/update/<int:id>/", views.MovieUpdateView.as_view()),
    path("movie/delete/<int:id>/", views.MovieDeleteView.as_view(), name="delete_movie"),
    path("member/update/<int:id>/", views.MemberUpdateView.as_view(), name="update_movie"),
    path("member/delete/<int:id>/", views.MemberDeleteView.as_view(), name="delete_member"),
    path("member/create/", views.MemberCreateView.as_view()),
    path("actors/", views.ActorView.as_view(), name="actors_view"),
    path("actor/create/", views.ActorCreateView.as_view()),
    path("actor/delete/<int:id>/", views.ActorDeleteView.as_view(), name='delete_actor'),
    path("actor/update/<int:id>/", views.ActorUpdateView.as_view()),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout")
]

my_lab/my_lab/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_lab/my_lab/apps/movie/models.py
import datetime
from django.db import models
from cloudinary.models import CloudinaryField
from django.utils import timezone
from datetime import date


class Category(models.Model):
    name = models.CharField("Category", max_length=150)
    description = models.TextField("Description")
    url = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Category"


class Actor(models.Model):
    name = models.CharField("Name", max_length=150)
    age = models.PositiveIntegerField("Age", default=0)
    imageURL = CloudinaryField("imageURL")
    description = models.TextField("Description")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actor"
        verbose_name_plural = "Actors"


class Movie(models.Model):
    title = models.CharField("Name", max_length=100)
    description = models.CharField("Description", max_length=300)
    genre = models.CharField(max_length=100, default="genre")
    imageURL = CloudinaryField("imageURL", null=True, blank=True)
    date_of_release = models.DateField("release date", default=date.today)
    actors = models.ManyToManyField(Actor, verbose_name="actor", related_name="film_actor")
    price = models.PositiveIntegerField(default=100)
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"


class Member(models.Model):
    member_name = models.CharField(max_length=100, verbose_name="Name")
    email_address = models.CharField(max_length=100, verbose_name="Email Address", null=True, unique=True)
    age = models.PositiveIntegerField(verbose_name="Age", null=True)
    birthday = models.DateTimeField(null=True)
    gender = models.CharField(max_length=100, null=True)
    member_join_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.member_name


class MovieRental(models.Model):
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name="Member Name")
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Movie Name")
    rent_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField()


class Producer(models.Model):
    producer_name = models.CharField(max_length=100, verbose_name="Name")
    age = models.PositiveIntegerField("Age", default=0)
    imageURL = models.ImageField("Image", upload_to="producers/")
    Biography = models.TextField("Bio")

    def __str__(self):
        return self.producer_name

    class Meta:
        verbose_name = "Producer"
        verbose_name_plural = "Producers"

my_lab/my_lab/apps/movie/views.py
import asyncio
from .async_functionality import *
from django.shortcuts import redirect
from django.views.generic.base import View
from django.shortcuts import render
from .models import Movie, Member, Actor
from . import forms
from .forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
import logging


logger = logging.getLogger('main')


class MoviesView(View):
    context_object_name = 'movie_list'

    def get_queryset(self):
        return Movie.objects.all()

    def get(self, request):
        logger.info('check MoviesView')
        search_query = request.GET.get('search', '')
        if search_query:
            movies = asyncio.run(get_filtered_movies(search_query))
        else:
            movies = asyncio.run(get_all_movies())
        return render(request, "movies/movie_index.html", {"movie_list": movies})


class RentView(View):
    def get(self, request):
        logger.info('check RentView')
        movies = asyncio.run(get_all_movies())
        return render(request, 'movies/rent_index.html', {"data": movies})


class MovieDetailView(View):
    def get(self, request, id):
        logger.info('check MovieDetailView')
        return render(request, "movies/details.html", {"movie": asyncio.run(get_movie_by_id(id))})


class MembersView(View):
    def get(self, request):
        logger.info('check MembersView')
        members = asyncio.run(get_all_members())
        return render(request, 'movies/member_index.html', {"data": members})


@method_decorator(login_required(login_url='login'), name='get')
class MovieRentalView(View):
    def get(self, request):
        logger.info('check MovieRentalView')
        if request.method == "GET":
            rent_form = forms.MovieRentalForm()
            return render(request, 'movies/rent_movie.html', {"rent_form": rent_form})

    def post(self, request):
        logger.info('check MovieRentalView')
        if request.method == "POST":
            rent_form = forms.MovieRentalForm(request.POST)
            if rent_form.is_valid():
                rent_form.save()
                success = {"strong": "Have a nice day bro!"}
                return render(request, "movies/order_success.html", {"success": success})
            return render(request, "movies/rent_movie.html", {"rent_form": rent_form})
        rent_form = forms.MovieRentalForm()
        return render(request, 'movies/rent_movie.html', {"rent_form": rent_form})


class MoveRentalSuccessView(View):
    def get(self, request):
        if request.method == "GET":
            success = {"strong": "Have a nice day bro!"}
            return render(request, "movies/order_success.html", {"success": success})


class MemberRentalInfoView(View):
    def get(self, request):
        logger.info('check MovieRentalInfoView')
        members = asyncio.run(get_all_members())
        return render(request, 'movies/member_rental_info.html', {"members": members, "data": None})

    def post(self, request):
        logger.info('check MovieRentalInfoView')
        members = asyncio.run(get_all_members())
        if request.method == "POST":
            member_id = int(request.POST.get("member"))
            if member_id:
                selected_member = members.get(id=member_id)
                return render(request, 'movies/member_rental_info.html',
                              {"members": members, "data": selected_member, "selected_value": member_id})
        members = asyncio.run(get_all_members())
        return render(request, 'movies/member_rental_info.html', {"members": members, "data": None})


@method_decorator(login_required(login_url='login'), name='get')
class MovieCreateView(View):
    def get(self, request):
        logger.info('check MovieCreateView')
        form = forms.MovieForm()
        return render(request, 'movies/movie_create.html', {"form": form})

    def post(self, request):
        logger.info('check MovieCreateView')
        if request.method == "POST":
            form = forms.MovieForm(request.POST, request.FILES)
            if form.is_valid():
                name = form.cleaned_data['title']
                form.imageURL = form.cleaned_data
                form.save()
                data = {"strong": f"Movie with name {name.title()} created", "simple": "this movie can now be rented"}
                return render(request, 'movies/movie_creation_success.html', {"data": data})
            return render(request, 'movies/movie_create.html', {"form": form})


@method_decorator(login_required(login_url='login'), name='get')
class MovieUpdateView(View):
    def get(self, request, id):
        logger.info('check MovieUpdateView')
        form = forms.MovieForm()
        return render(request, 'movies/movie_update.html', {'movie': asyncio.run(get_movie_by_id(id)), 'form': form})

    def post(self, request, id):
        logger.info('check MovieUpdateView')
        form = forms.MovieForm(request.POST, instance=asyncio.run(get_movie_by_id(id)))
        if form.is_valid():
            form.save()
            return redirect('/movies/')
        else:
            return request(305)


@method_decorator(login_required(login_url='login'), name='get')
class MovieDeleteView(View):
    def get(self, request, id):
        logger.info('check MovieDeleteView')
        return render(request, 'movies/movie_delete.html', {'movie': asyncio.run(get_movie_by_id(id))})

    def post(self, request, id):
        logger.info('check MovieDeleteView')
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/movies/')


@method_decorator(login_required(login_url='login'), name='get')
class MemberUpdateView(View):
    def get(self, request, id):
        logger.info('check MemberUpdateView')
        form = forms.MemberForm()
        return render(request, 'movies/member_update.html', {'member': asyncio.run(get_member_by_id(id)), 'form': form})

    def post(self, request, id):
        logger.info('check MemberUpdateView')
        form = forms.MemberForm(request.POST or None, instance=asyncio.run(get_member_by_id(id)))
        if form.is_valid():
            form.save()
            return redirect('/members/')


@method_decorator(login_required(login_url='login'), name='get')
class MemberDeleteView(View):
    def get(self, request, id):
        logger.info('check MemberDeleteView')
        return render(request, 'movies/member_delete.html', {'member': asyncio.run(get_member_by_id(id))})

    def post(self, request, id):
        logger.info('check MemberDeleteView')
        member = Member.objects.get(id=id)
        member.delete()
        return redirect('/members/')


@method_decorator(login_required(login_url='login'), name='get')
class MemberCreateView(View):
    def get(self, request):
        logger.info('check MemberCreateView')
        form = forms.MemberForm()
        return render(request, 'movies/member_create.html', {'form': form})

    def post(self, request):
        logger.info('check MemberCreateView')
        form = forms.MemberForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['member_name']
            form.save()
            data = {"strong": f"Member with name {name.title()} created", "simple": "you can now start renting movies"}
            return render(request, 'movies/movie_creation_success.html', {"data": data})
        return render(request, 'movies/member_create.html', {"form": form})


class ActorView(View):
    context_object_name = 'actor_list'

    def get_queryset(self):
        return Actor.objects.all()

    def get(self, request):
        logger.info('check ActorView')
        actors = asyncio.run(get_all_actors())
        return render(request, 'movies/actor_index.html', {"actor_list": actors})


@method_decorator(login_required(login_url='login'), name='get')
class ActorCreateView(View):
    def get(self, request):
        logger.info('check ActorCreateView')
        form = forms.ActorForm()
        return render(request, 'movies/actor_create.html', {'form': form})

    def post(self, request):
        logger.info('check ActorCreateView')
        form = forms.ActorForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            form.save()
            data = {"strong": f"Actor with name {name.title()} created"}
            return render(request, 'movies/movie_creation_success.html', {'data': data})
        return render(request, 'movies/actor_create.html', {'form': form})


@method_decorator(login_required(login_url='login'), name='get')
class ActorDeleteView(View):
    def get(self, request, id):
        logger.info('check ActorDeleteView')
        return render(request, 'movies/actor_delete.html', {'actor': asyncio.run(get_actor_by_id(id))})

    def post(self, request, id):
        logger.info('check ActorDeleteView')
        actor = Actor.objects.get(id=id)
        actor.delete()
        return redirect('/actors/')


@method_decorator(login_required(login_url='login'), name='get')
class ActorUpdateView(View):
    def get(self, request, id):
        logger.info('check ActorUpdateView')
        form = forms.ActorForm()
        return render(request, 'movies/actor_update.html', {'actor': asyncio.run(get_actor_by_id(id)), 'form': form})

    def post(self, request, id):
        logger.info('check ActorUpdateView')
        form = forms.ActorForm(request.POST, instance=asyncio.run(get_actor_by_id(id)))
        if form.is_valid():
            form.save()
            return redirect('/actors/')


class RegisterView(View):
    def get(self, request):
        logger.info('check RegisterView')
        if request.user.is_authenticated:
            return redirect('home')
        else:
            form = UserForm()
            context = {'form': form}

my_lab/my_lab/apps/movie/templates/movies/actor_create.html
{% extends "movies/base.html" %}
{% block title %}
    <title>Create New Actor</title>
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        <h1>Create <span class="badge bg-dark">Actor</span></h1>
        {% if form %}
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Create</button>
            </form>
        {% endif %}
    </div>
{% endblock content %}

my_lab/my_lab/apps/movie/templates/movies/actor_delete.html
{% extends "movies/base.html" %}

{% block title %}
    {% if actor %}
        <title>Delete {{actor.name}}</title>
    {% else %}
        <title>Delete Actor</title>
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        {% if actor %}
            <h1>Delete <span class="badge bg-dark">{{actor.name}}</span></h1>
            <p>Are you sure that you to delete this actor?</p>
            <form method="POST", action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </div>
            </form>
        {% else %}
            <h1>Actor not found</h1>
        {% endif %}
    </div>
{% endblock content %}

my_lab/my_lab/apps/movie/templates/movies/actor_update.html
{% extends "movies/base.html" %}

{% block title %}
    {% if actor %}
        <title>Update {{actor.name}}</title>
    {% else %}
        <title>Update Actor</title>
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        {% if actor %}
            <h1>Update <span class="badge bg-dark">{{actor.name}}</span></h1>
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class = "text-center mb-3">
                    <button type="submit" class="btn btn-dark">Update</button>
                </div>
            </form>
        {% else %}
            <h1>Actor not found</h1>
        {% endif %}

    </div>
{% endblock content %}

my_lab/my_lab/apps/movie/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        {% block title %}
        {% endblock %}

        {% block style %}
        {% endblock %}
    </head>
    <body style="background-color:#fae2bf">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <a class="navbar-brand" href="/" style="padding-left: 15px;">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarTogglerDemo02">
                      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                              <a class="nav-link" href="/members/">View Members</a>
                            </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="/movies/">View Movies</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item active">
                              <a class="nav-link" href="/rent/">Rent Movies</a>
                            </li>
                        {% endif %}
                        <li class="nav-item active">
                          <a class="nav-link" href="/member/rental">Movies Rented</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/actors/">Actors</a>
                        </li>
                      </ul>
                      <form class="d-flex input-group w-auto float-right" action="{% url 'movie_views' %}" style="margin-left:650px">
                          <input class="form-control rounded" type="search" placeholder="Search for a movie.." aria-label="Search" aria-describedby="search-addon" name="search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                      </form>
                        {% if not request.user.is_authenticated %}
                           <li style="margin-left:230px">
                                <a class="nav-link btn btn-outline-success my-2 my-sm-0" href="/login/">
                                    <i class="bi bi-box-arrow-in-right"></i>Log in
                                </a>
                           </li>
                           <li style="margin-right:20px">
                               <a class="nav-link btn btn-outline-primary my-2 my-sm-0" href="/register/">
                                   <i class="bi bi-person-plus"></i>Register
                               </a>
                           </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <li style="margin-left:150px">
                                <span style="color:white">Hello, {{request.user}}</span>
                            </li>
                            <li style="margin-right:10px">
                               <a class="nav-link btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout' %}">Log out</a>
                            </li>
                        {% endif %}
                </div>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </body>
</html>

my_lab/my_lab/apps/movie/templates/movies/details.html
{% extends "movies/base.html" %}
{% load static %}
<html lang="en">
{% block title %}
<head>
    <meta charset="UTF-8">
    <title>Movie Details</title>
</head>
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-dark">
                        <p class="card-text">
                            <h5 class="card-title">
                                {% if movie %}
                                    {{ movie.title }}
                                {% else %}
                                    <h1>Not Found</h1>
                                {% endif %}
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    {% if movie %}
                    <img src="{{movie.imageURL.url}}" width="100%" alt="{{movie.title}}">
                    {% endif %}
                </div>
                <div class="col-md-5">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Description:</b>
                            {% if movie %}
                                {{movie.description}}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            <b>Genre:</b>
                            {% if movie %}
                                {{movie.genre}}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            <b>Release:</b>
                            {% if movie %}
                                {{movie.date_of_release}}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                {% for actor in movie.actors.all %}
                                    <div class="column text-left">
                                        <div style="margin-right: 10px">
                                            <img class="border-info rounded-circle" src="{{ actor.imageURL.url}}" width="150px">
                                        </div>
                                        <br />
                                        <p class="card-text" style="margin-left:20px">{{actor.name}}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

my_lab/my_lab/apps/movie/templates/movies/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #fae2bf !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #f8c06b;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #00000;
			
		}

		.login_btn {
			width: 100%;
			background: #000000 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOG IN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="" autocomplete="off">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
				</div>

                    {% for message in messages %}
                        <p id="messages" style="color: white">{{message}}</p>
                    {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

my_lab/my_lab/apps/movie/templates/movies/member_rental_info.html
{% extends "movies/base.html" %}

{% block title %}
    <title>Member Rental Info</title>
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        {% if members %}
            <h1 >Rental <span class="badge bg-dark">Info</span></h1>
            <form method="POST" action="">
                {% csrf_token %}
                <p>
                    <label>Member Name</label>
                </p>
                </p>
                    <select name="member" class="form-control">
                        {% for member in members %}
                            <option value="{{ member.id }}">{{ member.member_name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <button type="submit" class="btn btn-dark">Submit</button>
            </form>
        {% endif %}

        {% if data %}
            <h1 class="mt-3">{{ data.member_name }}</h1>
            <table class="table table-striped">
                <thead>
                    <tr class="bg-dark" style="color: white;">
                        <th scope="col">Movie Name</th>
                        <th scope="col">Movie Genre</th>
                        <th scope="col">Rent Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Movie Fee</th>
                    </tr>
                </thead>
                <tbody>
                    {% for rental_info in data.movierental_set.all %}
                        <tr>
                            <td>{{ rental_info.movie_id.title }}</td>
                            <td>{{ rental_info.movie_id.genre }}</td>
                            <td>{{ rental_info.rent_date }}</td>
                            <td>{{ rental_info.return_date }}</td>
                            <td>{{ rental_info.movie_id.price }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock content %}

my_lab/my_lab/apps/movie/templates/movies/rent_index.html
{% extends "movies/base.html" %}

{% block title %}
<head>
    <title>Main page</title>
</head>
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        <h1>Movie <span class="badge bg-dark">Rental Info</span></h1>

        {% if data %}
            {% for movies in data %}
                <h5>
                    <li>
                        <img src="{{movies.imageURL.url}}" width="70px"class="align-middle"/> {{ movies.title }}, {{ movies.date_of_release}}
                    </li>
                </h5>

                <table class="table table-striped">
                    <thead>
                        <tr class="bg-dark" style="color: white;">
                            <th scope="col">Customer Name</th>
                            <th scope="col">Rent Date</th>
                            <th scope="col">Return Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rental_info in movies.movierental_set.all %}
                            <tr>
                                <td class="align-middle">{{ rental_info.member_id.member_name }}</td>
                                <td>{{ rental_info.rent_date }}</td>
                                <td>{{ rental_info.return_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}